### ISSUE TITLE
package seems broken on node v6.1.0

### ISSUE THREAD

**Issue by mbroadst** [http-auth/apache-md5#3]
```
mbroadst@retinoid:apache-md5 (master=)$ node --version
v6.1.0
```

```
mbroadst@retinoid:apache-md5 (master=)$ ./node_modules/.bin/nodeunit tests/

test-apache-md5
✖ testValidPassword

Assertion Message: Wrong password!
AssertionError: '$apr1$cF.rAvCe$EFsZZ.cfdo9ZUH15fLTVc/' == '$apr1$cF.rAvCe$YlzjmK4qu/ia6hC8CNfnm/'
    at Object.equal (/Users/mbroadst/Development/apache-md5/node_modules/nodeunit/lib/types.js:83:39)
    at Object.module.exports.testValidPassword (/Users/mbroadst/Development/apache-md5/tests/test-apache-md5.js:9:14)
    at Object.<anonymous> (/Users/mbroadst/Development/apache-md5/node_modules/nodeunit/lib/core.js:236:16)
    at /Users/mbroadst/Development/apache-md5/node_modules/nodeunit/lib/core.js:236:16
    at Object.exports.runTest (/Users/mbroadst/Development/apache-md5/node_modules/nodeunit/lib/core.js:70:9)
    at /Users/mbroadst/Development/apache-md5/node_modules/nodeunit/lib/core.js:118:25
    at /Users/mbroadst/Development/apache-md5/node_modules/nodeunit/deps/async.js:513:13
    at iterate (/Users/mbroadst/Development/apache-md5/node_modules/nodeunit/deps/async.js:123:13)
    at async.forEachSeries (/Users/mbroadst/Development/apache-md5/node_modules/nodeunit/deps/async.js:139:9)
    at _concat (/Users/mbroadst/Development/apache-md5/node_modules/nodeunit/deps/async.js:512:9)

✔ testInValidPassword

FAILURES: 1/2 assertions failed (25ms)
```

I haven't looked into this at all, but it definitely appears broken

**Comment by mbroadst** [comment]
Seems that the version of v8 included with node 6 includes subtle changes to utf16 string hanling, your use of `charCodeAt` appears to return different results on different node versions.

**Comment by mbroadst** [comment]
fixed in https://github.com/http-auth/apache-md5/pull/4

**Comment by gevorg** [comment]
Thanks!
